### ISSUE TITLE
no cmake cuda provide

### ISSUE THREAD

**Issue by jinfagang** [traveller59/spconv#4]
Error:

```
- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 35, in run
    self.build_extension(ext)
  File "setup.py", line 65, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_PREFIX_PATH=./libtorch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

```

**Comment by traveller59** [comment]
consider using [this](https://github.com/jetsonhacks/buildLibrealsense2TX/issues/13)?

**Comment by jinfagang** [comment]
Seems there still some errors:


```
[ 85%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
nvcc fatal   : Unknown option 'Wl,--no-as-needed,/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv/libtorch/lib/libcaffe2.so'
src/spconv/CMakeFiles/spconv.dir/build.make:192: recipe for target 'src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o] Error 1
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 92%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 92%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 35, in run
    self.build_extension(ext)
  File "setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

```

**Comment by traveller59** [comment]
```Wl,--no-as-needed``` should be solved in cmake 3.13+... are you using newest cmake? I am using cmake 3.13.2

**Comment by wyjforwjy** [comment]
Do you solve the problem? @jinfagang .I am also get the same error.  hope for your help.

**Comment by qchenclaire** [comment]
> Seems there still some errors:
> 
> ```
> [ 85%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
> nvcc fatal   : Unknown option 'Wl,--no-as-needed,/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv/libtorch/lib/libcaffe2.so'
> src/spconv/CMakeFiles/spconv.dir/build.make:192: recipe for target 'src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o' failed
> make[2]: *** [src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o] Error 1
> CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
> make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 92%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
> [ 92%] Built target spconv_utils
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> Traceback (most recent call last):
>   File "setup.py", line 82, in <module>
>     zip_safe=False,
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 140, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
>     self.run_command('build_ext')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 35, in run
>     self.build_extension(ext)
>   File "setup.py", line 66, in build_extension
>     subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
>   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
> ```

Solve this by addiing one line in the Cmakelist.txt
set(CMAKE_CUDA_COMPILER "/usr/local/cuda/bin/nvcc")
This should be added before the line 5
'if (SPCONV_BuildCUDA)'

I passed this error but still getting other errors... continue debugging...

**Comment by turtleMaster20** [comment]
The solution by @qchenclaire works. I think this issue can be closed
